name: Deploy n8n
on:
  push:
    branches: [ n8n ]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_AI }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_AI }}
          aws_default_region: us-east-1

          env_ghs: ${{ secrets.DOT_ENV }}


          aws_r53_enable: true
          aws_r53_domain_name: bitovi-ai.com
          aws_r53_sub_domain_name: n8n
          aws_r53_create_sub_cert: true

          aws_elb_app_port: 5678
          aws_elb_healthcheck: "HTTP:5678"  # ?